name = "sturnidae"
version = "1.0.0"
description = "Binding to Starling Bank's API"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "sturnidae" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
  { title = "Starling", href = "https://www.starlingbank.com/" },
  { title = "Starling's API docs", href = "https://developer.starlingbank.com/docs" },
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
